name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # каждые 10 минут
  workflow_dispatch:         # возможность запустить вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Render
        run: curl -s https://ntn-test.onrender.com/get_product_by_id?product_id=832298 > /dev/null
